---
- hosts: 172.31.25.239
  become: yes
  tasks:
   - name: I will to execute direct command
     command: hostname -f
     register: myresult

   - name: I want to display result
     debug:
       msg: "{{myresult}}"  

   - name: I want to install git
     apt:
       name: git
       state: present
     when: myresult.stderr == ""  

   - name: I want to instally tree
     apt:
       name: tree
       state: present    
     when: myresult.stderr == ""       