---
- hosts: 172.31.25.239
  become: yes
  tasks:
    - include_tasks: myfile.yml
    - name: copy file on nodes
      copy:
       src: testing1.yml
       dest: /home/jay/testing1.yml

    - name: I want to install apache server on my node 
      apt:
        name: apache2
        state: absent

    - name: I want to change the Output screen of my node
      template:
        src: myoutputcontent.j2
        dest: /var/www/html/index.html      

