---
- hosts: 172.31.92.30
  become: yes
  tasks:
    - include_tasks: myfile.yml
    - name: copy file on nodes
      copy:
       src: testing1.yml
       dest: /home/jay/testing1.yml

    - name: I want to install Redhat server on my node 
      apt:
        name: httpd
        state: present

    
    

