---
- name: Create a tomcat user
  user:
   name: tomcat
   shell: /bin/false
   home: /opt/tomcat
   state: present

- name: Update Packages
  apt:
    update_cache: yes

- name: Install JAVA
  apt:
    name: default-jdk
    state: present
